### ISSUE TITLE
Jupiters moon 'S/2011 J 1' returns invalid JSON

### ISSUE THREAD

**Issue by apsamuel** [systeme-solaire/api-rest#5]
```python
# works
>>> req = cURL.get('https://api.le-systeme-solaire.net/rest/bodies/eirene')

>>> json.loads(req.text)
{'id': 'eirene', 'name': 'Eiréné', 'englishName': 'Eirene', 'isPlanet': False, 'moons': None, 'semimajorAxis': 23493000, 'perihelion': 0, 'aphelion': 0, 'eccentricity': 0.22, 'inclination': 163.1, 'mass': {'massValue': 9.0, 'massExponent': 13}, 'vol': {'volValue': 0.0, 'volExponent': 0}, 'density': 1.0, 'gravity': 0, 'escape': 0, 'meanRadius': 2.0, 'equaRadius': 0, 'polarRadius': 0, 'flattening': 0, 'dimension': '', 'sideralOrbit': 759.7, 'sideralRotation': 0, 'aroundPlanet': {'planet': 'jupiter', 'rel': 'https://api.le-systeme-solaire.net/rest/bodies/jupiter'}, 'discoveredBy': 'Scott S. Sheppard, David C. Jewitt', 'discoveryDate': '2003', 'alternativeName': 'S/2003 J 5', 'axialTilt': 0}

>>> req.text
'{"id":"eirene","name":"Eiréné","englishName":"Eirene","isPlanet":false,"moons":null,"semimajorAxis":23493000,"perihelion":0,"aphelion":0,"eccentricity":0.22000,"inclination":163.10000,"mass":{"massValue":9.00000, "massExponent":13},"vol":{"volValue":0.00000, "volExponent":0},"density":1.00000,"gravity":0,"escape":0,"meanRadius":2.00000,"equaRadius":0,"polarRadius":0,"flattening":0,"dimension":"","sideralOrbit":759.70000,"sideralRotation":0,"aroundPlanet":{"planet":"jupiter", "rel":"https://api.le-systeme-solaire.net/rest/bodies/jupiter"},"discoveredBy":"Scott S. Sheppard, David C. Jewitt","discoveryDate":"2003","alternativeName":"S/2003 J 5","axialTilt":0}'

# fails
>>> req = cURL.get('https://api.le-systeme-solaire.net/rest/bodies/s2011j1')

>>> req.text
'{"id":"s2011j1","name":"S/2011 J 1","englishName":"S/2011 J 1","isPlanet":false,"moons":null,"semimajorAxis":20 155 290,"perihelion":0,"aphelion":0,"eccentricity":0.29600,"inclination":162.80000,"mass":{"massValue":2.40000, "massExponent":16},"vol":{"volValue":0.00000, "volExponent":0},"density":1.00000,"gravity":0,"escape":0,"meanRadius":0.50000,"equaRadius":0,"polarRadius":0,"flattening":0,"dimension":"","sideralOrbit":580.70000,"sideralRotation":0,"aroundPlanet":{"planet":"jupiter", "rel":"https://api.le-systeme-solaire.net/rest/bodies/jupiter"},"discoveredBy":"Scott S. Sheppard","discoveryDate":"29/01/2012","alternativeName":"S/2011 J 1","axialTilt":0}'

>>> json.loads(req.text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 113 (char 112)
```

The semimajorAxis values are not properly quoted `"semimajorAxis":20 155 290`

i checked around bodies.php, but it looks right, could the data source possibly have an errant entry?

**Comment by duduluu** [comment]
Same errors, invalid whitespaces in `semimajorAxis` number.


```
  "id": "s2011j1",
  "name": "S/2011 J 1",
  "englishName": "S/2011 J 1",
  "isPlanet": false,
  "moons": null,
  "semimajorAxis": 20 155 290,
```

```
  "id": "s2004s27",
  "name": "S/2004 S 27",
  "englishName": "",
  "isPlanet": false,
  "moons": null,
  "semimajorAxis": 19 7767 00,
```

```
  "id": "s2004s29",
  "name": "S/2004 S 29",
  "englishName": "",
  "isPlanet": false,
  "moons": null,
  "semimajorAxis": 17 4707 00,
```

**Comment by khrys63** [comment]
Hi

thanks for feedback.

I just fix data in DB.
